# NEXUS Platform - Kubernetes Configuration SSOT Anchor
# Generated: 2025-01-27T12:30:00Z
# Version: 1.0

metadata:
  anchor_id: "k8s_config"
  family: "deployment"
  description: "Kubernetes deployment and service configuration"
  format: "yaml"
  owner: "@nexus-devops-team"
  version: "v1.0.0"
  centrality_score: 0.90

namespace:
  name: "nexus-platform"
  labels:
    app: "nexus"
    environment: "production"

configmaps:
  nexus-config:
    data:
      database_url: "postgresql://nexus:password@postgres:5432/nexus"
      redis_url: "redis://redis:6379"
      api_base_url: "https://api.nexus.com"
      environment: "production"

secrets:
  nexus-secrets:
    type: "Opaque"
    data:
      database_password: "<base64-encoded>"
      redis_password: "<base64-encoded>"
      jwt_secret: "<base64-encoded>"

deployments:
  nexus-backend:
    replicas: 3
    selector:
      matchLabels:
        app: "nexus-backend"
    template:
      metadata:
        labels:
          app: "nexus-backend"
      spec:
        containers:
          - name: "backend"
            image: "nexus/backend:latest"
            ports:
              - containerPort: 8000
            env:
              - name: "DATABASE_URL"
                valueFrom:
                  configMapKeyRef:
                    name: "nexus-config"
                    key: "database_url"
              - name: "REDIS_URL"
                valueFrom:
                  configMapKeyRef:
                    name: "nexus-config"
                    key: "redis_url"
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            livenessProbe:
              httpGet:
                path: "/health"
                port: 8000
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: "/ready"
                port: 8000
              initialDelaySeconds: 5
              periodSeconds: 5

services:
  nexus-backend-service:
    selector:
      app: "nexus-backend"
    ports:
      - port: 80
        targetPort: 8000
    type: "ClusterIP"
