apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nexus-backend-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nexus-backend-role
subjects:
  - kind: ServiceAccount
    name: nexus-backend-sa
    namespace: nexus-platform
