apiVersion: v1
kind: ResourceQuota
metadata:
  name: nexus-quota
  namespace: nexus-platform
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "4"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
