apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nexus-local
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nexus-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_API_URL
        - name: REACT_APP_WS_URL
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_WS_URL
        - name: REACT_APP_AI_URL
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_AI_URL
        - name: REACT_APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_ENVIRONMENT
        - name: REACT_APP_DEBUG_MODE
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_DEBUG_MODE
        - name: REACT_APP_ENABLE_ANALYTICS
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_ENABLE_ANALYTICS
        - name: REACT_APP_ENABLE_NOTIFICATIONS
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_ENABLE_NOTIFICATIONS
        - name: REACT_APP_ENABLE_FILE_UPLOAD
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_ENABLE_FILE_UPLOAD
        - name: REACT_APP_ENABLE_REAL_TIME
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: REACT_APP_ENABLE_REAL_TIME
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: nexus-local
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
