apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nexus-local
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nexus-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: REDIS_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nexus-secrets
                  key: JWT_SECRET_KEY
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: nexus-secrets
                  key: ENCRYPTION_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nexus-secrets
                  key: SECRET_KEY
            - name: NEXUS_ENV
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: NEXUS_ENV
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: DEBUG
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: LOG_LEVEL
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: CORS_ALLOWED_ORIGINS
            - name: CORS_ALLOW_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: CORS_ALLOW_CREDENTIALS
            - name: CORS_ALLOWED_METHODS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: CORS_ALLOWED_METHODS
            - name: CORS_ALLOWED_HEADERS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: CORS_ALLOWED_HEADERS
            - name: RATE_LIMIT_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: RATE_LIMIT_REQUESTS
            - name: RATE_LIMIT_WINDOW
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: RATE_LIMIT_WINDOW
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: TRUSTED_HOSTS
            - name: ENABLE_AUDIT_LOGGING
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: ENABLE_AUDIT_LOGGING
            - name: PROMETHEUS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: PROMETHEUS_ENABLED
            - name: PROMETHEUS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: PROMETHEUS_PORT
            - name: WORKERS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: WORKERS
            - name: WORKER_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: WORKER_CONNECTIONS
            - name: MAX_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: MAX_REQUESTS
            - name: TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: nexus-config
                  key: TIMEOUT
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: nexus-local
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
