global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them against the currently ingested data.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A list of scrape configurations.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to all metrics scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend-staging'
    static_configs:
      - targets: ['nexus-backend-staging:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'frontend-staging'
    static_configs:
      - targets: ['nexus-frontend-staging:80']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'nginx-staging'
    static_configs:
      - targets: ['nexus-nginx-staging:80/nginx_health']
    metrics_path: /nginx_health
    scrape_interval: 30s

  - job_name: 'postgres-staging'
    static_configs:
      - targets: ['nexus-postgres-staging:5432']
    scrape_interval: 30s

  - job_name: 'redis-staging'
    static_configs:
      - targets: ['nexus-redis-staging:6379']
    scrape_interval: 30s
