# Nexus Consolidated Automation System Configuration

# System Settings
system:
  name: "Nexus Consolidated Automation"
  version: "1.0.0"
  workspace_path: "/Users/Arief/Desktop/Nexus"
  master_todo_path: ".nexus/ssot/master/master_todo.md"

# Queue Configuration
queue:
  max_queue_size: 300
  min_queue_size: 50
  refill_threshold: 0.2 # Refill when queue drops below 20% of max

# Worker Configuration
workers:
  min_workers: 6
  max_workers: 20
  target_cpu: 75.0
  scaling:
    cpu_threshold_low: 60.0
    cpu_threshold_high: 85.0
    memory_threshold: 80.0
    scale_up_delay: 5.0 # seconds
    scale_down_delay: 10.0 # seconds

# Worker Specializations
worker_types:
  database:
    count: 3
    priority: high
    success_rate: 0.95
  api:
    count: 4
    priority: high
    success_rate: 0.90
  frontend:
    count: 3
    priority: medium
    success_rate: 0.92
  testing:
    count: 3
    priority: medium
    success_rate: 0.88
  monitoring:
    count: 2
    priority: high
    success_rate: 0.97
  general:
    count: 5
    priority: low
    success_rate: 0.90

# Task Processing
processing:
  cycle_duration: 2.0 # seconds
  max_retries: 3
  retry_delay: 1.0 # seconds
  complexity_analysis: true
  subtask_breakdown: true

# File Management
file_updates:
  batch_size: 100
  update_interval: 1.0 # seconds
  backup_enabled: true
  backup_interval: 300 # seconds

# Monitoring
monitoring:
  interval: 3.0 # seconds
  metrics_history_size: 1000
  alert_thresholds:
    cpu_high: 90.0
    memory_high: 85.0
    queue_empty: 10
    error_rate_high: 20.0

# Logging
logging:
  level: "INFO"
  file: "consolidated_automation.log"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance
performance:
  enable_profiling: false
  profile_interval: 60.0 # seconds
  memory_optimization: true
  cpu_optimization: true

# Security
security:
  enable_encryption: false
  enable_authentication: false
  rate_limiting: true
  max_requests_per_minute: 1000

# Features
features:
  intelligent_scaling: true
  task_prioritization: true
  error_recovery: true
  health_monitoring: true
  metrics_collection: true
  alerting: true
  web_interface: false
  api_endpoints: false
