apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-main.yaml
  - deployment-glassmorphism.yaml
  - deployment-cyberpunk.yaml
  - deployment-modern.yaml
  - service-main.yaml
  - service-glassmorphism.yaml
  - service-cyberpunk.yaml
  - service-modern.yaml
  - ingress.yaml

commonLabels:
  app: nexus-frontend
  version: v1.0.0
