apiVersion: v1
kind: Secret
metadata:
  name: nexus-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL25leHVzOnBhc3N3b3JkQG5leHVzLWRiOjU0MzIvbmV4dXM=
  redis-url: cmVkaXM6Ly9uZXh1cy1yZWRpczo2Mzc5
  api-key: bmV4dXMtYXBpLWtleQ==
