apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: nexus
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
  type: ClusterIP
