apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-backend
  namespace: nexus-platform-dev
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: CORS_ORIGINS
          value: "http://localhost:3000,http://localhost:3001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
