# Filebeat configuration for NEXUS Platform
# Ships logs from containers and files to Logstash

filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: true
    exclude_lines: ['^\s*$'] # Exclude empty lines

  - type: log
    enabled: true
    paths:
      - /var/log/nexus/*.log
      - /app/logs/*.log
    fields:
      service: nexus-backend
      environment: production
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log
    fields:
      service: nginx
      environment: production
    fields_under_root: true

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: true
  worker: 2

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Processors
processors:
  - add_host_metadata:
      netinfo.enabled: true
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# Monitoring
http.enabled: true
http.host: 0.0.0.0
http.port: 5066
