apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: nexus
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true

  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'NEXUS'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards

  dashboard.json: |
    {
      "dashboard": {
        "title": "NEXUS Platform Overview",
        "tags": ["nexus", "platform"],
        "timezone": "browser",
        "panels": [
          {
            "title": "API Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"nexus-ssot-main\"}[5m]))",
                "legendFormat": "95th percentile"
              }
            ]
          },
          {
            "title": "Error Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{status=~\"5..\", job=\"nexus-ssot-main\"}[5m]) / rate(http_requests_total{job=\"nexus-ssot-main\"}[5m]) * 100",
                "legendFormat": "Error rate %"
              }
            ]
          },
          {
            "title": "Database Connections",
            "type": "graph",
            "targets": [
              {
                "expr": "pg_stat_activity_count{datname=\"nexus\"}",
                "legendFormat": "Active connections"
              }
            ]
          }
        ]
      }
    }
