# Nexus Platform Prometheus Alert Rules
groups:
  - name: nexus-platform.rules
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      # Disk Space Low
      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is above 90% on {{ $labels.instance }} mount {{ $labels.mountpoint }}"

      # Service Down
      - alert: ServiceDown
        expr: up{job="nexus-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Nexus Backend service is down"
          description: "Nexus Backend service has been down for more than 1 minute"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time"
          description: "95th percentile response time is above 2 seconds for more than 5 minutes"

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate"
          description: "Error rate is above 5% for more than 5 minutes"

      # Database Connection Issues
      - alert: DatabaseConnectionIssues
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection issues"
          description: "Cannot connect to PostgreSQL database"

      # Redis Connection Issues
      - alert: RedisConnectionIssues
        expr: redis_up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Redis connection issues"
          description: "Cannot connect to Redis"

      # High Database Connections
      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Database connections are above 80% of maximum for more than 5 minutes"

      # Slow Database Queries
      - alert: SlowDatabaseQueries
        expr: histogram_quantile(0.95, rate(pg_stat_database_tup_returned[5m])) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries"
          description: "95th percentile database query time is above 1 second for more than 5 minutes"

      # High Redis Memory Usage
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is above 80% for more than 5 minutes"

      # Container Restart
      - alert: ContainerRestart
        expr: rate(container_start_time_seconds[1h]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Container restart detected"
          description: "Container {{ $labels.name }} has restarted"

      # Out of Memory
      - alert: OutOfMemory
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes * 100 > 95
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Container out of memory"
          description: "Container {{ $labels.name }} is using more than 95% of its memory limit"

      # High Network Traffic
      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) > 100000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High network traffic"
          description: "Network receive traffic is above 100MB/s for more than 5 minutes on {{ $labels.instance }}"

      # SSL Certificate Expiry
      - alert: SSLCertificateExpiry
        expr: (ssl_cert_not_after - time()) / 86400 < 30
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value }} days"

      # Blackbox Probe Failures
      - alert: BlackboxProbeFailure
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Blackbox probe failure"
          description: "Blackbox probe failed for {{ $labels.instance }}"

      # High Queue Depth
      - alert: HighQueueDepth
        expr: redis_list_length > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High queue depth"
          description: "Queue depth is above 1000 for more than 5 minutes"

      # Database Lock Contention
      - alert: DatabaseLockContention
        expr: pg_locks_count > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database lock contention"
          description: "High number of database locks detected for more than 5 minutes"

      # Cache Hit Rate Low
      - alert: LowCacheHitRate
        expr: redis_keyspace_hits / (redis_keyspace_hits + redis_keyspace_misses) * 100 < 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is below 80% for more than 10 minutes"
