# NEXUS Platform - Environment Configuration
# Centralized environment management for all services

# Development Environment
development:
  database:
    host: localhost
    port: 5432
    name: nexus_dev
    user: nexus
    password: password
    ssl_mode: disable
    pool_size: 5
    max_overflow: 10
    pool_timeout: 30
    pool_recycle: 3600

  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
    max_connections: 10
    socket_timeout: 5
    socket_connect_timeout: 5
    retry_on_timeout: true

  api:
    host: 0.0.0.0
    port: 8000
    workers: 1
    reload: true
    log_level: debug
    cors_origins: ["http://localhost:3000"]
    cors_allow_credentials: true
    cors_allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    cors_allow_headers: ["*"]

  frontend:
    host: 0.0.0.0
    port: 3000
    api_url: http://localhost:8000
    websocket_url: ws://localhost:8000/ws
    log_level: debug
    hot_reload: true

  security:
    jwt_secret: "dev-secret-key-change-in-production"
    jwt_algorithm: "HS256"
    jwt_access_token_expire_minutes: 30
    jwt_refresh_token_expire_days: 7
    password_min_length: 8
    password_require_uppercase: true
    password_require_lowercase: true
    password_require_numbers: true
    password_require_special: true
    max_login_attempts: 5
    lockout_duration_minutes: 15

  monitoring:
    enabled: true
    prometheus_port: 9090
    grafana_port: 3001
    log_level: info
    metrics_interval: 30
    health_check_interval: 10

  logging:
    level: debug
    format: json
    file: /app/logs/nexus.log
    max_size: 100MB
    max_files: 5
    compress: true

# Staging Environment
staging:
  database:
    host: postgres-staging.example.com
    port: 5432
    name: nexus_staging
    user: nexus
    password: "staging-password"
    ssl_mode: require
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600

  redis:
    host: redis-staging.example.com
    port: 6379
    password: "staging-redis-password"
    db: 0
    max_connections: 20
    socket_timeout: 5
    socket_connect_timeout: 5
    retry_on_timeout: true

  api:
    host: 0.0.0.0
    port: 8000
    workers: 4
    reload: false
    log_level: info
    cors_origins: ["https://staging.nexus.example.com"]
    cors_allow_credentials: true
    cors_allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    cors_allow_headers: ["*"]

  frontend:
    host: 0.0.0.0
    port: 3000
    api_url: https://api-staging.nexus.example.com
    websocket_url: wss://api-staging.nexus.example.com/ws
    log_level: info
    hot_reload: false

  security:
    jwt_secret: "staging-secret-key"
    jwt_algorithm: "HS256"
    jwt_access_token_expire_minutes: 30
    jwt_refresh_token_expire_days: 7
    password_min_length: 8
    password_require_uppercase: true
    password_require_lowercase: true
    password_require_numbers: true
    password_require_special: true
    max_login_attempts: 5
    lockout_duration_minutes: 15

  monitoring:
    enabled: true
    prometheus_port: 9090
    grafana_port: 3001
    log_level: info
    metrics_interval: 30
    health_check_interval: 10

  logging:
    level: info
    format: json
    file: /app/logs/nexus.log
    max_size: 100MB
    max_files: 10
    compress: true

# Production Environment
production:
  database:
    host: postgres-prod.example.com
    port: 5432
    name: nexus_prod
    user: nexus
    password: "production-password"
    ssl_mode: require
    pool_size: 20
    max_overflow: 30
    pool_timeout: 30
    pool_recycle: 3600

  redis:
    host: redis-prod.example.com
    port: 6379
    password: "production-redis-password"
    db: 0
    max_connections: 50
    socket_timeout: 5
    socket_connect_timeout: 5
    retry_on_timeout: true

  api:
    host: 0.0.0.0
    port: 8000
    workers: 8
    reload: false
    log_level: warning
    cors_origins: ["https://nexus.example.com"]
    cors_allow_credentials: true
    cors_allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    cors_allow_headers: ["*"]

  frontend:
    host: 0.0.0.0
    port: 3000
    api_url: https://api.nexus.example.com
    websocket_url: wss://api.nexus.example.com/ws
    log_level: warning
    hot_reload: false

  security:
    jwt_secret: "production-secret-key"
    jwt_algorithm: "HS256"
    jwt_access_token_expire_minutes: 15
    jwt_refresh_token_expire_days: 7
    password_min_length: 12
    password_require_uppercase: true
    password_require_lowercase: true
    password_require_numbers: true
    password_require_special: true
    max_login_attempts: 3
    lockout_duration_minutes: 30

  monitoring:
    enabled: true
    prometheus_port: 9090
    grafana_port: 3001
    log_level: warning
    metrics_interval: 30
    health_check_interval: 5

  logging:
    level: warning
    format: json
    file: /app/logs/nexus.log
    max_size: 100MB
    max_files: 30
    compress: true

# Test Environment
test:
  database:
    host: localhost
    port: 5432
    name: nexus_test
    user: nexus
    password: password
    ssl_mode: disable
    pool_size: 2
    max_overflow: 5
    pool_timeout: 30
    pool_recycle: 3600

  redis:
    host: localhost
    port: 6379
    password: ""
    db: 1
    max_connections: 5
    socket_timeout: 5
    socket_connect_timeout: 5
    retry_on_timeout: true

  api:
    host: 0.0.0.0
    port: 8000
    workers: 1
    reload: false
    log_level: debug
    cors_origins: ["http://localhost:3000"]
    cors_allow_credentials: true
    cors_allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    cors_allow_headers: ["*"]

  frontend:
    host: 0.0.0.0
    port: 3000
    api_url: http://localhost:8000
    websocket_url: ws://localhost:8000/ws
    log_level: debug
    hot_reload: false

  security:
    jwt_secret: "test-secret-key"
    jwt_algorithm: "HS256"
    jwt_access_token_expire_minutes: 30
    jwt_refresh_token_expire_days: 7
    password_min_length: 8
    password_require_uppercase: false
    password_require_lowercase: false
    password_require_numbers: false
    password_require_special: false
    max_login_attempts: 10
    lockout_duration_minutes: 1

  monitoring:
    enabled: false
    prometheus_port: 9090
    grafana_port: 3001
    log_level: debug
    metrics_interval: 30
    health_check_interval: 10

  logging:
    level: debug
    format: json
    file: /app/logs/nexus.log
    max_size: 10MB
    max_files: 2
    compress: false

# Environment-specific overrides
overrides:
  # Common overrides for all environments
  common:
    app_name: "NEXUS Platform"
    app_version: "3.0.0"
    app_description: "NEXUS Platform - Financial Management System"

  # Development overrides
  development:
    debug: true
    testing: true
    mock_external_apis: true

  # Staging overrides
  staging:
    debug: false
    testing: true
    mock_external_apis: false

  # Production overrides
  production:
    debug: false
    testing: false
    mock_external_apis: false

  # Test overrides
  test:
    debug: true
    testing: true
    mock_external_apis: true
