# Frenly AI Meta Configuration
# Configuration for Frenly AI as a Meta AI operating above the automation system

frenly_ai_meta:
  # Learning Configuration
  learning:
    enabled: true
    analysis_interval: "daily" # daily, weekly, monthly
    learning_rate: 0.1
    memory_retention_days: 90
    min_data_points: 100
    confidence_threshold: 0.8

  # Prediction Configuration
  prediction:
    enabled: true
    forecast_horizon_days: 30
    confidence_threshold: 0.8
    prediction_types:
      - "repository_growth"
      - "optimization_needs"
      - "performance_trends"
      - "resource_requirements"

  # Recommendation Configuration
  recommendations:
    enabled: true
    suggestion_frequency: "weekly" # daily, weekly, monthly
    min_confidence: 0.7
    max_recommendations: 10
    recommendation_types:
      - "optimization"
      - "configuration"
      - "workflow"
      - "best_practices"

  # Adaptive Configuration
  adaptation:
    enabled: true
    auto_apply_threshold: 0.9 # Only auto-apply if confidence >= 0.9
    parameter_adjustment_rate: 0.1
    rollback_on_failure: true

  # Meta AI Thresholds
  meta_ai_thresholds:
    learning_trigger:
      min_data_points: 100
      min_time_window: "7 days"
      confidence_threshold: 0.8

    recommendation_trigger:
      min_analysis_complete: true
      min_confidence: 0.7
      impact_threshold: "medium" # low, medium, high

    prediction_trigger:
      min_patterns_learned: 5
      min_confidence: 0.8
      forecast_accuracy_threshold: 0.75

  # Analysis Configuration
  analysis:
    audit_log_analysis:
      enabled: true
      lookback_days: 30
      pattern_detection: true

    performance_analysis:
      enabled: true
      metrics_tracking: true
      bottleneck_detection: true

    optimization_analysis:
      enabled: true
      efficiency_tracking: true
      space_savings_analysis: true

  # Notification Configuration
  notifications:
    enabled: true
    channels:
      - "audit_log"
      - "recommendations_file"
      - "system_console"

    notification_triggers:
      high_confidence_recommendation: true
      prediction_accuracy_alert: true
      learning_milestone: true
      system_anomaly: true

  # Data Storage Configuration
  data_storage:
    learning_data_path: "frenly_ai_meta/learning_data"
    patterns_path: "frenly_ai_meta/patterns"
    predictions_path: "frenly_ai_meta/predictions"
    recommendations_path: "frenly_ai_meta/recommendations"

    retention_policy:
      learning_data_days: 365
      patterns_days: 180
      predictions_days: 90
      recommendations_days: 30

  # Advanced Features
  advanced:
    machine_learning:
      enabled: true
      algorithm: "pattern_recognition" # pattern_recognition, neural_network, decision_tree
      training_data_minimum: 1000
      model_update_frequency: "weekly"

    natural_language_processing:
      enabled: false # Future feature
      command_processing: false
      description_analysis: false

    autonomous_operation:
      enabled: false # Future feature
      auto_apply_recommendations: false
      auto_adapt_parameters: false
      emergency_rollback: true
