# NEXUS Security Configuration
version: "1.0.0"
environment: "production"

# Security Headers
security_headers:
  enabled: true
  strict_mode: true
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
  x_frame_options: "DENY"
  x_content_type_options: "nosniff"
  x_xss_protection: "1; mode=block"
  strict_transport_security: "max-age=31536000; includeSubDomains"

# CORS Configuration
cors:
  enabled: true
  allowed_origins:
    - "https://nexus-platform.com"
    - "https://app.nexus-platform.com"
    - "http://localhost:3000"
    - "http://localhost:3001"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  credentials: true

# Rate Limiting
rate_limiting:
  enabled: true
  default_limit: 100
  window_size: 60
  burst_limit: 200
  endpoints:
    "/api/auth/login": 10
    "/api/auth/register": 5
    "/api/insights": 50
    "/api/monitoring": 30

# JWT Configuration
jwt:
  secret_key: "${JWT_SECRET_KEY}"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  issuer: "nexus-platform"

# MFA Configuration
mfa:
  enabled: true
  required_for_admin: true
  backup_codes_count: 10
  totp_window: 1

# Encryption
encryption:
  enabled: true
  algorithm: "AES-256-GCM"
  key_rotation_days: 90

# Security Scanning
security_scanning:
  enabled: true
  scan_interval_minutes: 60
  vulnerability_threshold: "medium"
  auto_fix: false

# Threat Detection
threat_detection:
  enabled: true
  suspicious_activity_threshold: 5
  ip_whitelist:
    - "127.0.0.1"
    - "::1"
  ip_blacklist: []

# Audit Logging
audit_logging:
  enabled: true
  log_level: "INFO"
  sensitive_fields:
    - "password"
    - "token"
    - "secret"
  retention_days: 90

# Security Policies
policies:
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    max_age_days: 90

  session_policy:
    max_duration_hours: 8
    idle_timeout_minutes: 30
    concurrent_sessions: 3

  api_policy:
    require_authentication: true
    require_authorization: true
    rate_limit_by_user: true
    log_all_requests: true
