apiVersion: v1
kind: Secret
metadata:
  name: nexus-tls
  namespace: nexus-platform
  labels:
    app: nexus-platform
    component: tls
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-tls-cert>
  tls.key: <base64-encoded-tls-key>
  ca.crt: <base64-encoded-ca-cert>
