apiVersion: v1
kind: Service
metadata:
  name: nexus-frontend
  namespace: nexus
  labels:
    app: nexus-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: nexus-frontend
