apiVersion: v1
kind: LimitRange
metadata:
  name: nexus-platform-limits
  namespace: nexus-platform
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 250m
      type: Container
