groups:
  - name: nexus_alerts
    rules:
      - alert: HighErrorRate
        annotations:
          description: Error rate is {{ $value }} errors per second
          summary: High error rate detected
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
      - alert: HighResponseTime
        annotations:
          description: 95th percentile response time is {{ $value }} seconds
          summary: High response time detected
        expr:
          histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
          > 1.0
        for: 5m
        labels:
          severity: warning
      - alert: HighCPUUsage
        annotations:
          description: CPU usage is {{ $value }}%
          summary: High CPU usage detected
        expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
      - alert: HighMemoryUsage
        annotations:
          description: Memory usage is {{ $value }}%
          summary: High memory usage detected
        expr:
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
          > 80
        for: 5m
        labels:
          severity: warning
