# NEXUS Platform - Prometheus Alerting Rules
# Comprehensive alerting rules for production monitoring

groups:
  - name: nexus-platform.rules
    rules:
      # High-level service availability
      - alert: ServiceDown
        expr: up{job=~"nexus-.*"} == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      # Backend API health
      - alert: BackendAPIUnhealthy
        expr: nexus_backend_health_status != 1
        for: 2m
        labels:
          severity: critical
          service: "nexus-backend"
        annotations:
          summary: "Backend API is unhealthy"
          description: "Backend API health check is failing for more than 2 minutes."

      # Database connectivity
      - alert: DatabaseConnectionFailed
        expr: postgres_up == 0
        for: 1m
        labels:
          severity: critical
          service: "postgres"
        annotations:
          summary: "Database connection failed"
          description: "Cannot connect to PostgreSQL database."

      # Redis connectivity
      - alert: RedisConnectionFailed
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          service: "redis"
        annotations:
          summary: "Redis connection failed"
          description: "Cannot connect to Redis cache."

      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: "nexus-backend"
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for more than 5 minutes."

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: "nexus-backend"
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds for more than 5 minutes."

      # Low request rate (potential issue)
      - alert: LowRequestRate
        expr: rate(http_requests_total[5m]) < 0.1
        for: 10m
        labels:
          severity: warning
          service: "nexus-backend"
        annotations:
          summary: "Low request rate detected"
          description: "Request rate is {{ $value }} requests per second for more than 10 minutes."

      # Database performance
      - alert: DatabaseHighConnections
        expr: postgres_stat_activity_count{state="active"} > 80
        for: 5m
        labels:
          severity: warning
          service: "postgres"
        annotations:
          summary: "High database connections"
          description: "Database has {{ $value }} active connections for more than 5 minutes."

      - alert: DatabaseSlowQueries
        expr: postgres_stat_activity_max_tx_duration > 300
        for: 2m
        labels:
          severity: warning
          service: "postgres"
        annotations:
          summary: "Slow database queries detected"
          description: "Database has queries running for more than {{ $value }} seconds."

      # Redis performance
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: "redis"
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is {{ $value | humanizePercentage }} for more than 5 minutes."

      - alert: RedisHighKeyExpiration
        expr: rate(redis_expired_keys_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
          service: "redis"
        annotations:
          summary: "High Redis key expiration rate"
          description: "Redis is expiring {{ $value }} keys per second for more than 5 minutes."

      # System resources
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: "system"
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: "system"
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% for more than 5 minutes."

      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: "system"
        annotations:
          summary: "Low disk space detected"
          description: "Disk usage is {{ $value }}% for more than 5 minutes."

      # Docker container health
      - alert: ContainerRestarting
        expr: rate(container_start_time_seconds[10m]) > 0
        for: 1m
        labels:
          severity: warning
          service: "docker"
        annotations:
          summary: "Container restarting frequently"
          description: "Container {{ $labels.name }} is restarting frequently."

      - alert: ContainerHighMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: "docker"
        annotations:
          summary: "Container high memory usage"
          description: "Container {{ $labels.name }} memory usage is {{ $value | humanizePercentage }} for more than 5 minutes."

      # Security alerts
      - alert: HighFailedLoginAttempts
        expr: rate(nexus_auth_failed_attempts_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: "security"
        annotations:
          summary: "High failed login attempts"
          description: "{{ $value }} failed login attempts per second for more than 2 minutes."

      - alert: SuspiciousActivity
        expr: rate(nexus_security_suspicious_requests_total[5m]) > 5
        for: 1m
        labels:
          severity: critical
          service: "security"
        annotations:
          summary: "Suspicious activity detected"
          description: "{{ $value }} suspicious requests per second detected."

      # Business logic alerts
      - alert: HighTransactionVolume
        expr: rate(nexus_transactions_total[5m]) > 1000
        for: 5m
        labels:
          severity: info
          service: "business"
        annotations:
          summary: "High transaction volume"
          description: "Transaction volume is {{ $value }} transactions per second for more than 5 minutes."

      - alert: UnusualTransactionPattern
        expr: rate(nexus_transactions_failed_total[5m]) / rate(nexus_transactions_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: "business"
        annotations:
          summary: "Unusual transaction failure rate"
          description: "Transaction failure rate is {{ $value | humanizePercentage }} for more than 5 minutes."

      # Backup alerts
      - alert: BackupFailed
        expr: nexus_backup_status != 1
        for: 1m
        labels:
          severity: critical
          service: "backup"
        annotations:
          summary: "Backup failed"
          description: "Backup process has failed."

      - alert: BackupOverdue
        expr: time() - nexus_backup_last_success_timestamp > 86400
        for: 1h
        labels:
          severity: warning
          service: "backup"
        annotations:
          summary: "Backup overdue"
          description: "Last successful backup was more than 24 hours ago."

      # Monitoring system health
      - alert: PrometheusTargetDown
        expr: up{job="prometheus"} == 0
        for: 1m
        labels:
          severity: critical
          service: "monitoring"
        annotations:
          summary: "Prometheus is down"
          description: "Prometheus monitoring system is down."

      - alert: GrafanaUnavailable
        expr: up{job="grafana"} == 0
        for: 5m
        labels:
          severity: warning
          service: "monitoring"
        annotations:
          summary: "Grafana is unavailable"
          description: "Grafana dashboard is unavailable for more than 5 minutes."

      # Network connectivity
      - alert: NetworkLatencyHigh
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 5
        for: 10m
        labels:
          severity: warning
          service: "network"
        annotations:
          summary: "High network latency"
          description: "95th percentile network latency is {{ $value }} seconds for more than 10 minutes."

      # SSL certificate expiration
      - alert: SSLCertificateExpiringSoon
        expr: (ssl_cert_not_after - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          service: "ssl"
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value }} days."

      - alert: SSLCertificateExpired
        expr: ssl_cert_not_after - time() < 0
        for: 1m
        labels:
          severity: critical
          service: "ssl"
        annotations:
          summary: "SSL certificate expired"
          description: "SSL certificate for {{ $labels.instance }} has expired."
