# Prometheus Configuration for Nexus Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "nexus-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Nexus Platform Backend
  - job_name: "nexus-backend"
    static_configs:
      - targets: ["nexus-backend:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor for container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Redis Exporter
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # PostgreSQL Exporter
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # AWS CloudWatch Exporter
  - job_name: "cloudwatch-exporter"
    static_configs:
      - targets: ["cloudwatch-exporter:9106"]

  # Blackbox Exporter for uptime monitoring
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://nexus-backend:8000/health
          - http://nexus-frontend:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
