// frontend/web/src/types/security.ts

export type SecurityEventType =
  | "LOGIN_SUCCESS"
  | "LOGIN_FAILURE"
  | "REGISTRATION_SUCCESS"
  | "REGISTRATION_FAILURE"
  | "PASSWORD_RESET_REQUEST"
  | "PASSWORD_RESET_SUCCESS"
  | "SESSION_VALIDATION_SUCCESS"
  | "SESSION_VALIDATION_FAILURE"
  | "LOGOUT_SUCCESS"
  | "UNAUTHORIZED_ACCESS"
  | "BRUTE_FORCE_ATTACK"
  | "SQL_INJECTION_ATTEMPT"
  | "XSS_ATTACK_ATTEMPT"
  | "DATA_BREACH_ALERT"
  | "SYSTEM_COMPROMISE"
  | "POLICY_VIOLATION"
  | "UNKNOWN_THREAT";

export type ThreatLevel = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
